apiVersion: apps/v1
kind: Deployment
metadata:
  name: techmarket-app-green
  labels:
    app: techmarket-orders
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techmarket-orders
      version: green
  template:
    metadata:
      labels:
        app: techmarket-orders
        version: green
    spec:
      containers:
      - name: techmarket-app
        image: techmarket-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_COLOR
          value: "Green-Environment"
        
        # ====== AGREGAR ESTO PARA SUSTENTAR EL INFORME (IL3.4) ======
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10